branches:
  only:
  - master
  - develop
language: java
jdk:
  - oraclejdk8
jobs:
  include:
    - stage: tests
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - chmod +x ./dockerbuild.sh
      script:
        - gradle check
        - gradle jacocoTestReport
      after_script:
        - cd src/main/java
        - ../../../cc-test-reporter format-coverage -d -t jacoco ../../../build/reports/jacoco/test/jacocoTestReport.xml
        - ../../../cc-test-reporter upload-coverage -d
    - stage: deploy to docker as snapshot and to heroku staging
      if: type = push AND branch = develop
      sudo: required
      services:
        - docker
      before_script:
        - chmod +x ./dockerbuild.sh
      script: ./dockerbuild.sh
